apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-http-ports: "80,5678"
  name: n8n
  namespace: n8n
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 5678
      protocol: TCP
  selector:
    service: n8n
