apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      service: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: n8n
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown 1000:1000 /data"]
          volumeMounts:
            - name: n8n-claim0
              mountPath: /data
      containers:
        - command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n start
          env:
            - name: N8N_HOST
              value: n8n.tenderpro.pl
            - name: N8N_PORT
              value: "5678"
            - name: WEBHOOK_URL
              value: https://n8n.tenderpro.pl
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: VUE_APP_URL_BASE_API
              value: https://n8n.tenderpro.pl
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: private-db-postgresql-fra1-74367-do-user-23066415-0.k.db.ondigitalocean.com
            - name: DB_POSTGRESDB_PORT
              value: "25060"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_PASSWORD
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "false"
            - name: DB_POSTGRESDB_SSL_ENABLED
              value: "true"
            - name: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
              value: "false"
            - name: N8N_LOG_LEVEL
              value: "debug"
            - name: N8N_SECURE_COOKIE
              value: "true"
            - name: LANGCHAIN_TRACING_V2
              value: "true"
            - name: LANGCHAIN_ENDPOINT
              value: https://api.smith.langchain.com
            - name: LANGCHAIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: langsmith-secret
                  key: LANGCHAIN_API_KEY
          image: n8nio/n8n
          name: n8n
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-claim0
      restartPolicy: Always
      volumes:
        - name: n8n-claim0
          persistentVolumeClaim:
            claimName: n8n-claim0
        - name: n8n-secret
          secret:
            secretName: n8n-secret
        - name: postgres-secret
          secret:
            secretName: postgres-secret
